# Numpy
This is probably the most efficient library regarding scientific computation with arrays and matrices in Python. 
### Arrays (ndarrays)
The fundamental structure in Numpy is a data type called ndarrays (n-dimensional arrays). These structures are similar to Python's basic lists, but they offer advantages in terms of memory usage and data access.
### Importing Numpy
The instruction to import all contents of `numpy` is

In [ ]:
import numpy as np # as np is the pseudonym

Now we play a bit with arrays.

In [ ]:
# one dimensional array (vector)
a=np.array([1,2,3,4,5])
# Operations with an array
print(a*4)
print(a+a)
print(a<3)
print(a**2)
print(a.T @ a)

And with 2-dimensional arrays, like 
$$b=\left(
    \begin{array}{c} 
    2 & 1 & 2\\\\
    1 & 4 & 1\\\\
    2 & 1 & 6
    \end{array} 
\right)$$

In [ ]:
b=np.array([[2,1,2],[1,4,1],[2,1,6]])
print(b)
# Printing dimension, shape and size
print("Dimension: %i"%b.ndim)
print("Shape: "+str(b.shape))
print("Size: %i"%b.size)

We can reshape an array:

In [ ]:
c = b.reshape(1,9)
c

In [ ]:
my_array=np.arange(0.5,12.6,0.5)
print(my_array)

In [ ]:
print(my_array.reshape(5,5))

Now we index the elements of the array in different ways.

In [ ]:
# Elements of the first column
print(my_array[:,0])
# Elements of the first row
print(my_array[0,:])
# Diagonal elements
print(my_array.diagonal())

### Random Arrays
`numpy` has dedicated methods to work with randon numbers. We will see some of them

In [ ]:
# Printing (uniform) random numbers
# from 0 to 1, in a 10x10 matrix
random_numbers=np.random.random(size=(10,10)) 

# Select the ones smaller or equal to 0.5:
less_or_equal=random_numbers[random_numbers<=0.5]
print(less_or_equal)
print(less_or_equal.size)

In [ ]:
print(np.random.uniform(-5, 12, size=(5,5))) #(lower lim, upper lim, shape)
print()
print(np.random.normal(5, 5, size=(5,5))) #(mean, std, shape)

### Linear algebra
Now let us see some common linear algebra operations.

In [ ]:
# a 3x3 matrix
matrix=np.array([[2,7,5],[0,9,8],[7,4,0]])
# Multiplying by the identity matrix
print(matrix.dot(np.eye(3,3)))

In [ ]:
# (Matrix)^2
print(matrix.dot(matrix),"\n", matrix @ matrix)

In [ ]:
# Matrix determinant
print(np.linalg.det(matrix))

### Intervals and Grids
Intervals have various applications, such as graphing or performing numerical integrations. Grids are two-dimensional intervals, useful when plotting three-dimensional surfaces. The methods for creating partitions are presented below.

The `meshgrid(a,b)` method creates a correspondence between all elements of a with all elements of b. This way, we create a two-dimensional surface, which is useful for graphing scalar fields of $F:\mathbb{R}^2\rightarrow \mathbb{R}$.

In [ ]:
espacio = np.linspace(0,10,100)
print(espacio)
X,Y = np.meshgrid(espacio,espacio)
print(X)
print()
print(Y)

### Solve a system of linear equations
Is easy to solve linear equation systems with **Numpy**, one can initialize the two matrices $A$ and $b$ that satisfies $Ax=b$ for an unique value of $x$. Notice that if the system is inconsistent or linearly dependent, **Numpy** will throw an error. Let's see some examples.

Suposse you want to solve the next linear equation system:

$$\left(
    \begin{array}{c} 
    3 & 1\\
    1 & 2 
    \end{array} 
\right)
\left(
    \begin{array}{c}
    x_1\\
    x_2
    \end{array}
\right)=
\left(
    \begin{array}{c}
    9\\
    8
    \end{array}
\right)$$
This is the way to do it.

In [24]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)

[2. 3.]


or

In [25]:
print(np.dot(np.linalg.inv(a),b))

[2. 3.]


### Eigenvalues and eigenvectors
Recall that an eigenvalue $\lambda$ (with resp. eigenvector $v$) of a matrix $A$ satisfies $$Av = \lambda v$. We can find the eigenvalues and eigenvectors of a given matrix using numpy.

In [27]:
w, v = np.linalg.eig(np.diag((1, 2, 3)))
print(w) #Where w is an array with the eigenvalues
print(v) #And v is a matrix with the eigenvectors

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Examples
1. Using numpy arrays, show all odd numbers between 1 and 3000.

2. Roll six six-sided dice many times. Numerically, what is the probability that two or more dice show the same number? If you roll seven six-sided dice, what is the probability that at least two of them show the same number?

3. Compute the dot product between two one-dimensional arrays of numbers.

4. Separate the perfect squares of the array
```python
a=np.array([4,5,7,49,34,36,21,16,101,121,169,100,82,33,81,64])
```